//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestCat
    {
        public string Id1 { get; set; }
        public int Check_cat { get; set; }
        public string Id { get; set; }
    
        public virtual Meo Meo { get; set; }
    }
}
