//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiMeo
    {
        public LoaiMeo()
        {
            this.Meos = new HashSet<Meo>();
        }
    
        public string Ma_Loai { get; set; }
        public string TenLoai { get; set; }
    
        public virtual ICollection<Meo> Meos { get; set; }
    }
}
